name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download and extract zrok
      run: |
        New-Item -ItemType Directory -Force .\zrok | Out-Null
        curl.exe -L -o zrok.tar.gz https://github.com/openziti/zrok/releases/download/v2.0.4/zrok_2.0.4_windows_amd64.tar.gz
        tar -xzf zrok.tar.gz -C .\zrok
        Get-ChildItem -Path .\zrok -Directory | ForEach-Object {
          Move-Item "$($_.FullName)\*" .\zrok\ -Force
          Remove-Item $_.FullName -Recurse -Force
        }
        Remove-Item zrok.tar.gz

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Enable zrok environment
      env:
        ZROK_TOKEN: ${{ secrets.ZROK_TOKEN }}
      run: .\zrok\zrok2.exe enable $env:ZROK_TOKEN

    - name: Create persistent private TCP tunnel
      shell: pwsh
      run: |
        # ایجاد یک tunnel TCP خصوصی با توکن ثابت و غیرفعال کردن حالت تعاملی (--headless)
        .\zrok\zrok2.exe share private --backend-mode tcpTunnel 127.0.0.1:3389 --headless *> zrok.log
        Get-Content zrok.log
      
